services:
  fairer-pages:
    container_name: fairer-pages
    image: prplanit/fairer-pages:latest # "latest" is not recommended! Explicitly tag the latest release, i.e.; v0.0.12.
    ports:
      - 8023:8080
    environment:
      LISTEN_PORT: "8080"
      LOG_LEVEL: "warn"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
