services:
  fairer-pages:
    container_name: fairer-pages
    build: .
    image: prplanit/fairer-pages:v0.0.12
    ports:
      - 8023:8080
    environment:
      LISTEN_PORT: "8080"
      LOG_LEVEL: "warn"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
